### ISSUE TITLE
Orthographic correction on Information page

### ISSUE THREAD

**Issue by julienhenzelin** [liquidconcept/contactautomoto-website#2]
Réf: http://www.contact-auto-moto.ch/informations.html

A) Ajouter "les" à la place de "le" dans "dans le meilleures conditions"
disposition afin que vos examens théoriques et pratiques se déroulent dans les meilleures conditions

B) Ajouter une bullet point complète en dernier de la liste "Dans notre salle de théorie vous trouverez :"
"Lieux d'activité : Région de Lausanne, Renens, Prilly, Morges, Gland, Nyon, Echallens, Yverdon, Moudon, Montreux, Vevey et Pully."

**Comment by simonwalther** [comment]
It has been fixed.
![issue2](https://cloud.githubusercontent.com/assets/2511106/5873921/1fe4a59e-a2fc-11e4-872e-f39508e1ca21.png)
