### ISSUE TITLE
Orthographic correction on cours page & moto page

### ISSUE THREAD

**Issue by julienhenzelin** [liquidconcept/contactautomoto-website#3]
Réf: http://www.contact-auto-moto.ch/cours.html

A) Enlever la phrase "au prix promotionnel de CHF 120.-" et mettre un point après "santé"
Les cours de premiers secours sont organisés 2 fois par mois environ, selon le nombre de participants, les soirs de semaine ou les vendredi soir et samedi toute la journée. Ces cours sont assurés uniquement par des professionnels de la santé au prix promotionnel de CHF 120.-

B) Ajouter un "S" à premier secours dans le bouton
Un "S" à premiers secours dans le bouton

Réf: http://www.contact-auto-moto.ch/moto.html

A) Ajouter un espace entre "utilisant" et "le formulaire"
Renseignements et inscriptions par téléphone au 078 621 81 82 ou en utilisant (ESPACE) le formulaire de contact

**Comment by simonwalther** [comment]
Fixed.
![issue3ab](https://cloud.githubusercontent.com/assets/2511106/5873850/252e7e5e-a2fb-11e4-9c23-39e60d975ba2.png)
![issue3c](https://cloud.githubusercontent.com/assets/2511106/5873849/252df3a8-a2fb-11e4-8f8e-7b308e59fec3.png)
