### ISSUE TITLE
Orthographic correction on renseignements page

### ISSUE THREAD

**Issue by julienhenzelin** [liquidconcept/contactautomoto-website#4]
Réf: http://www.contact-auto-moto.ch/renseignements.html

A) Make "Renseignements sur les prochains cours" a title

B) Move "(sensibilisation uniquement si vous possédez déjà le permis d'élève conducteur)" under the point "Sensibilisation" as below
Sensibilisation : cours sur 1 semaine tous les mois environ. (sensibilisation uniquement si vous possédez déjà le permis d'élève conducteur)

C) Suppress "Inscription au moyen du formulaire de contact ou par téléphone" from the line
Premiers secours : cours organisés 2 fois par mois, les soirs de semaine ou les vendredi soir et samedi toute la journée. => supprimer (Inscription au moyen du formulaire de contact ou par téléphone)

D) Add an "S" at premiers secours in the button
Un "S" à premiers secours dans le bouton

E) Correct the name "boutton" in "bouton" in the sentence
Pour vous inscrire directement chez Firstmed, utilisez le bouton ci-dessous :

F) Use "ci-dessous" in stead of "ci-joint"
Inscriptions par téléphone au 078 621 81 82 ou en utilisant le formulaire ci-dessous.

**Comment by simonwalther** [comment]
These issues have been fixed.
![issue4abc](https://cloud.githubusercontent.com/assets/2511106/5873726/ddaf7ef8-a2f9-11e4-8404-0de208aecf9a.png)
![issue4de](https://cloud.githubusercontent.com/assets/2511106/5873724/ddae875a-a2f9-11e4-9117-2d8222f315dd.png)
![issue4f](https://cloud.githubusercontent.com/assets/2511106/5873725/ddaf0b4e-a2f9-11e4-843c-c094d6e1e8b8.png)
