### ISSUE TITLE
Orthographic correction on home page

### ISSUE THREAD

**Issue by julienhenzelin** [liquidconcept/contactautomoto-website#5]
Réf: http://www.contact-auto-moto.ch/index.html

A) Add "(Cossonay, Savigny)" after "différents centres de formation de la région."
différents centres de formation de la région. (Cossonay, Savigny)

**Comment by simonwalther** [comment]
It has been fixed 
![issue5](https://cloud.githubusercontent.com/assets/2511106/5873442/b18c72c0-a2f6-11e4-9506-f62457b34fc9.png)
