### ISSUE TITLE
Correct the email link on all page

### ISSUE THREAD

**Issue by julienhenzelin** [liquidconcept/contactautomoto-website#6]
Il semblerait que ce n'est pas un "mailto" pour le mail info@contac-auto-moto.ch dans la barre de gauche en bas.

**Comment by simonwalther** [comment]
The link is fixed now.
![issue6](https://cloud.githubusercontent.com/assets/2511106/5873532/d5f85722-a2f7-11e4-8e35-e50af43b3845.png)
